import { Inter } from "next/font/google";
import "./globals.css";
import MyContext from "@/Provider/MyContext";
import AuthProvider from "./services/AuthProvider";
import NavBar from "./Shared/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyContext>
          {/* <AuthProvider> */}        
          <NavBar/>   
            {children}
          {/* </AuthProvider> */}
        </MyContext>
      </body>
    </html>
  );
}
